plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'jp.ac.meijou.android.groupb_lg_'
    compileSdk 35

    defaultConfig {
        applicationId "jp.ac.meijou.android.groupb_lg_"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.constraintlayout)
    implementation(libs.activity.ktx)

    coreLibraryDesugaring(libs.desugar.jdk.libs)

    implementation(libs.datastore.preferences)
    implementation(libs.datastore.preferences.rxjava3)
    implementation(libs.okhttp)
    implementation(libs.moshi)
    implementation(libs.room.runtime)
    annotationProcessor(libs.room.compiler)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.test.core)

    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}